version: 2

sources:
  - name: nyc_taxi
    schema: main

    tables:
      - name: yellow_tripdata
        identifier: yellow_tripdata
        description: "Data mentah perjalanan taksi Yellow Cab NYC bulanan."
